language: php

php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

services:
  - rabbitmq

install:
  - echo | pecl install -f amqp-1.7.0

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then bin/phpspec run; fi
  - bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache
