language: php

matrix:
  include:
    - php: 5.5
    - php: 5.6
      env: COLLECT_COVERAGE=true
    - php: 7.0

sudo: false

services:
  - rabbitmq

install:
  - echo | pecl install -f amqp-1.7.0

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - if [[ $TRAVIS_PHP_VERSION != '7.0' && $COLLECT_COVERAGE != 'true' ]]; then bin/phpspec run; fi
  - if [[ $TRAVIS_PHP_VERSION != '7.0' && $COLLECT_COVERAGE == 'true' ]]; then bin/phpspec run --config phpspec.yml.ci; fi
  - bin/phpunit

after_script:
  - if [[ $COLLECT_COVERAGE == 'true' ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

cache:
  directories:
    - $HOME/.composer/cache
