language: php

matrix:
  include:
    - php: 7.0
    - php: 7.1
      env: COLLECT_COVERAGE=true
    - php: 7.2

sudo: false

services:
  - rabbitmq

install:
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt-get update
  - sudo apt-get install -y librabbitmq-dev
  - echo | pecl install -f amqp-1.9.3

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - if [[ $COLLECT_COVERAGE != 'true' ]]; then bin/phpspec run; fi
  - if [[ $COLLECT_COVERAGE == 'true' ]]; then bin/phpspec run --config phpspec.yml.ci; fi
  - bin/phpunit

after_script:
  - if [[ $COLLECT_COVERAGE == 'true' ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

cache:
  directories:
    - $HOME/.composer/cache
